import { ActionButton } from "@/components/ui/ActionControl";
import { AdminHeader, AdminNotice, AdminPanel, EmptyState, StatusBadge, formatDate, formatMoney } from "@/components/admin/AdminUi";
import { createInvoiceAction, updateInvoiceAction } from "@/features/admin/actions";
import { getAdminInvoices } from "@/features/admin/data";

type Props = { searchParams: Promise<{ error?: string; message?: string }> };

export default async function InvoicesPage({ searchParams }: Props) {
  const params = await searchParams;
  const { invoices, organizations, projects, proposals } = await getAdminInvoices();
  const outstanding = invoices.reduce((sum, invoice) => sum + Math.max(0, Number(invoice.amount_due) - Number(invoice.amount_paid)), 0);
  return (
    <section>
      <AdminHeader title="Invoice tracking." text={`Track drafts, due dates, manual payments, and outstanding balances. Current outstanding: ${formatMoney(outstanding)}.`} />
      <AdminNotice error={params.error} message={params.message} />
      <div className="mt-8 grid gap-6 xl:grid-cols-[.72fr_1.28fr]">
        <AdminPanel eyebrow="New invoice" title="Create invoice record">
          <form action={createInvoiceAction} className="mt-6 grid gap-4"><label className="grid gap-2 text-sm text-white/55">Invoice number<input name="invoiceNumber" required placeholder="GS-2026-001" className="form-field" /></label><label className="grid gap-2 text-sm text-white/55">Organization<select name="organizationId" required className="form-field"><option value="">Select organization</option>{organizations.map((organization) => <option key={organization.id} value={organization.id}>{organization.name}</option>)}</select></label><label className="grid gap-2 text-sm text-white/55">Project<select name="projectId" className="form-field"><option value="">No project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label className="grid gap-2 text-sm text-white/55">Proposal<select name="proposalId" className="form-field"><option value="">No proposal</option>{proposals.map((proposal) => <option key={proposal.id} value={proposal.id}>{proposal.title} — {formatMoney(proposal.total, proposal.currency)}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm text-white/55">Amount due<input name="amountDue" type="number" min="0" step="0.01" required className="form-field" /></label><label className="grid gap-2 text-sm text-white/55">Currency<input name="currency" defaultValue="CAD" className="form-field" /></label></div><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm text-white/55">Issued<input name="issuedAt" type="datetime-local" className="form-field" /></label><label className="grid gap-2 text-sm text-white/55">Due<input name="dueAt" type="datetime-local" className="form-field" /></label></div><label className="grid gap-2 text-sm text-white/55">Notes<textarea name="notes" rows={3} className="form-field resize-y" /></label><ActionButton type="submit">Create invoice</ActionButton></form>
        </AdminPanel>
        <AdminPanel eyebrow="Billing" title="Invoices">
          <div className="mt-6 grid gap-4">{invoices.length ? invoices.map((invoice) => { const organization = Array.isArray(invoice.organizations) ? invoice.organizations[0] : invoice.organizations; const project = Array.isArray(invoice.projects) ? invoice.projects[0] : invoice.projects; return <article key={invoice.id} className="rounded-2xl border border-white/[.07] bg-black/10 p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-medium text-white">{invoice.invoice_number}</p><p className="mt-1 text-sm text-white/35">{organization?.name || "Organization"}{project?.name ? ` · ${project.name}` : ""}</p></div><div className="flex items-center gap-3"><StatusBadge value={invoice.status} /><span className="font-medium text-white">{formatMoney(invoice.amount_due, invoice.currency)}</span></div></div><div className="mt-4 grid gap-4 sm:grid-cols-[1fr_1fr_auto]"><div className="text-xs text-white/28">Paid {formatMoney(invoice.amount_paid, invoice.currency)}<br />Due {formatDate(invoice.due_at)}</div><div className="text-xs text-white/28">Issued {formatDate(invoice.issued_at)}<br />{invoice.notes || "No notes"}</div><form action={updateInvoiceAction} className="grid gap-2 sm:min-w-[240px]"><input type="hidden" name="invoiceId" value={invoice.id} /><select name="status" defaultValue={invoice.status} className="form-field">{["draft","open","paid","overdue","void"].map((status) => <option key={status} value={status}>{status}</option>)}</select><input name="amountPaid" type="number" min="0" step="0.01" defaultValue={invoice.amount_paid} className="form-field" aria-label="Amount paid" /><input name="notes" defaultValue={invoice.notes ?? ""} className="form-field" aria-label="Invoice notes" /><button type="submit" className="justify-self-end text-xs font-medium text-[#8be9ff] hover:text-white">Save invoice →</button></form></div></article>; }) : <EmptyState>No invoices yet.</EmptyState>}</div>
        </AdminPanel>
      </div>
    </section>
  );
}
