export type Service = { slug:string; number:string; title:string; shortTitle:string; summary:string; deliverables:string[]; idealFor:string };
export const services: Service[] = [
  { slug:"business-websites", number:"01", title:"Business Website Design & Development", shortTitle:"Business Websites", summary:"Distinctive, conversion-focused websites that make established businesses look credible, modern, and valuable.", deliverables:["Strategy and sitemap","Custom responsive design","Next.js development","Lead-generation forms","SEO and performance foundation"], idealFor:"Local and professional service businesses ready to outgrow a template website." },
  { slug:"website-redesign", number:"02", title:"Strategic Website Redesign", shortTitle:"Website Redesign", summary:"A complete visual, structural, and technical upgrade for websites that no longer represent the quality of the business.", deliverables:["Current-site audit","Information architecture","New visual system","Content migration","Redirect and launch plan"], idealFor:"Established companies with an outdated, slow, or underperforming website." },
  { slug:"landing-pages", number:"03", title:"Campaign & Landing Pages", shortTitle:"Landing Pages", summary:"Focused pages designed around one offer, one audience, and one measurable conversion goal.", deliverables:["Offer positioning","Conversion copy structure","Custom page design","Analytics events","Form or checkout integration"], idealFor:"Paid campaigns, product launches, lead magnets, and service promotions." },
  { slug:"client-portals", number:"04", title:"Client Portals & Dashboards", shortTitle:"Portals & Dashboards", summary:"Secure product-like experiences for clients, teams, reporting, approvals, documents, and workflows.", deliverables:["Authentication","Role-based access","Database architecture","Dashboard interface","Business integrations"], idealFor:"Businesses replacing spreadsheets, email chains, and disconnected tools." },
  { slug:"full-stack-apps", number:"05", title:"Custom Full-Stack Web Applications", shortTitle:"Web Applications", summary:"Purpose-built applications with thoughtful UX, secure data, and scalable foundations.", deliverables:["Product planning","Application UX","Frontend and backend","Database and permissions","Deployment and monitoring"], idealFor:"Founders and companies building a digital product or internal system." },
  { slug:"care-plans", number:"06", title:"Website Care & Growth", shortTitle:"Care Plans", summary:"Ongoing technical ownership, improvements, content updates, reporting, and priority support.", deliverables:["Updates and monitoring","Content changes","Performance checks","Analytics reporting","Priority support"], idealFor:"Clients who want one reliable technical partner after launch." }
];
export const getServiceBySlug=(slug:string)=>services.find(s=>s.slug===slug);
