import Link from "next/link";
import { ActionButton } from "@/components/ui/ActionControl";
import { AdminHeader, AdminNotice, AdminPanel, EmptyState, StatusBadge } from "@/components/admin/AdminUi";
import { upsertBlogPostAction, upsertCaseStudyAction, upsertServiceContentAction, upsertTestimonialAction } from "@/features/admin/actions";
import { getAdminContent } from "@/features/admin/data";

type Props = { searchParams: Promise<{ tab?: string; error?: string; message?: string }> };
const tabs = ["services", "cases", "testimonials", "posts"] as const;

export default async function ContentPage({ searchParams }: Props) {
  const params = await searchParams;
  const tab = tabs.includes((params.tab ?? "services") as (typeof tabs)[number]) ? (params.tab ?? "services") : "services";
  const data = await getAdminContent();
  return (
    <section>
      <AdminHeader title="Content management." text="Manage services, case studies, testimonials, and insights without editing source files." />
      <AdminNotice error={params.error} message={params.message} />
      <div className="mt-7 flex flex-wrap gap-2">{tabs.map((item) => <Link key={item} href={`/admin/content?tab=${item}`} className={`rounded-full border px-4 py-2 text-xs uppercase tracking-[.16em] transition ${tab === item ? "border-[#8be9ff]/50 bg-[#8be9ff]/10 text-[#8be9ff]" : "border-white/10 text-white/36 hover:border-white/25 hover:text-white"}`}>{item}</Link>)}</div>

      {tab === "services" ? <div className="mt-7 grid gap-6 xl:grid-cols-[.7fr_1.3fr]"><AdminPanel eyebrow="New service" title="Add service"><ServiceForm /></AdminPanel><AdminPanel eyebrow="Website" title="Services"><div className="mt-6 grid gap-4">{data.services.length ? data.services.map((item) => <ServiceForm key={item.id} item={item} />) : <EmptyState>No services yet.</EmptyState>}</div></AdminPanel></div> : null}
      {tab === "cases" ? <div className="mt-7 grid gap-6 xl:grid-cols-[.7fr_1.3fr]"><AdminPanel eyebrow="New case study" title="Add project story"><CaseForm /></AdminPanel><AdminPanel eyebrow="Portfolio" title="Case studies"><div className="mt-6 grid gap-4">{data.cases.length ? data.cases.map((item) => <CaseForm key={item.id} item={item} compact />) : <EmptyState>No case studies yet.</EmptyState>}</div></AdminPanel></div> : null}
      {tab === "testimonials" ? <div className="mt-7 grid gap-6 xl:grid-cols-[.7fr_1.3fr]"><AdminPanel eyebrow="New testimonial" title="Add client quote"><TestimonialForm projects={data.projects} /></AdminPanel><AdminPanel eyebrow="Social proof" title="Testimonials"><div className="mt-6 grid gap-4">{data.testimonials.length ? data.testimonials.map((item) => <TestimonialForm key={item.id} item={item} projects={data.projects} />) : <EmptyState>No testimonials yet.</EmptyState>}</div></AdminPanel></div> : null}
      {tab === "posts" ? <div className="mt-7 grid gap-6 xl:grid-cols-[.7fr_1.3fr]"><AdminPanel eyebrow="New article" title="Add insight"><PostForm /></AdminPanel><AdminPanel eyebrow="Insights" title="Articles"><div className="mt-6 grid gap-4">{data.posts.length ? data.posts.map((item) => <PostForm key={item.id} item={item} />) : <EmptyState>No articles yet.</EmptyState>}</div></AdminPanel></div> : null}
    </section>
  );
}

function ServiceForm({ item }: { item?: { id: string; slug: string; title: string; summary: string; position: number; published: boolean } }) {
  return <form action={upsertServiceContentAction} className="grid gap-3 rounded-2xl border border-white/[.07] bg-black/10 p-4">{item ? <input type="hidden" name="id" value={item.id} /> : null}<div className="flex items-center justify-between gap-3">{item ? <StatusBadge value={item.published ? "published" : "draft"} /> : <span className="text-xs text-white/25">Draft</span>}<label className="flex items-center gap-2 text-xs text-white/45"><input name="published" type="checkbox" defaultChecked={item?.published} /> Published</label></div><input name="title" required defaultValue={item?.title ?? ""} placeholder="Service title" className="form-field" /><input name="slug" required defaultValue={item?.slug ?? ""} placeholder="service-slug" className="form-field" /><textarea name="summary" required rows={4} defaultValue={item?.summary ?? ""} placeholder="Service summary" className="form-field resize-y" /><input name="position" type="number" defaultValue={item?.position ?? 0} className="form-field" /><ActionButton type="submit">{item ? "Save service" : "Create service"}</ActionButton></form>;
}

function CaseForm({ item, compact = false }: { item?: { id: string; slug: string; title: string; category: string | null; summary: string; challenge: string | null; approach: string | null; outcome: string | null; cover_image: string | null; featured: boolean; published: boolean }; compact?: boolean }) {
  return <form action={upsertCaseStudyAction} className="grid gap-3 rounded-2xl border border-white/[.07] bg-black/10 p-4">{item ? <input type="hidden" name="id" value={item.id} /> : null}<div className="flex flex-wrap items-center justify-between gap-3">{item ? <StatusBadge value={item.published ? "published" : "draft"} /> : <span className="text-xs text-white/25">Draft</span>}<div className="flex gap-4"><label className="flex items-center gap-2 text-xs text-white/45"><input name="featured" type="checkbox" defaultChecked={item?.featured} /> Featured</label><label className="flex items-center gap-2 text-xs text-white/45"><input name="published" type="checkbox" defaultChecked={item?.published} /> Published</label></div></div><input name="title" required defaultValue={item?.title ?? ""} placeholder="Case study title" className="form-field" /><div className="grid gap-3 sm:grid-cols-2"><input name="slug" required defaultValue={item?.slug ?? ""} placeholder="case-study-slug" className="form-field" /><input name="category" defaultValue={item?.category ?? ""} placeholder="Category" className="form-field" /></div><textarea name="summary" required rows={3} defaultValue={item?.summary ?? ""} placeholder="Summary" className="form-field resize-y" />{!compact ? <><textarea name="challenge" rows={3} defaultValue={item?.challenge ?? ""} placeholder="Challenge" className="form-field resize-y" /><textarea name="approach" rows={3} defaultValue={item?.approach ?? ""} placeholder="Approach" className="form-field resize-y" /><textarea name="outcome" rows={3} defaultValue={item?.outcome ?? ""} placeholder="Outcome" className="form-field resize-y" /></> : <><input type="hidden" name="challenge" value={item?.challenge ?? ""} /><input type="hidden" name="approach" value={item?.approach ?? ""} /><input type="hidden" name="outcome" value={item?.outcome ?? ""} /></>}<input name="coverImage" defaultValue={item?.cover_image ?? ""} placeholder="Cover image URL" className="form-field" /><ActionButton type="submit">{item ? "Save case study" : "Create case study"}</ActionButton></form>;
}

function TestimonialForm({ item, projects }: { item?: { id: string; client_name: string; company: string | null; quote: string; project_id: string | null; published: boolean; position: number }; projects: Array<{ id: string; name: string }> }) {
  return <form action={upsertTestimonialAction} className="grid gap-3 rounded-2xl border border-white/[.07] bg-black/10 p-4">{item ? <input type="hidden" name="id" value={item.id} /> : null}<div className="flex items-center justify-between gap-3">{item ? <StatusBadge value={item.published ? "published" : "draft"} /> : <span className="text-xs text-white/25">Draft</span>}<label className="flex items-center gap-2 text-xs text-white/45"><input name="published" type="checkbox" defaultChecked={item?.published} /> Published</label></div><input name="clientName" required defaultValue={item?.client_name ?? ""} placeholder="Client name" className="form-field" /><input name="company" defaultValue={item?.company ?? ""} placeholder="Company" className="form-field" /><textarea name="quote" required rows={4} defaultValue={item?.quote ?? ""} placeholder="Client quote" className="form-field resize-y" /><select name="projectId" defaultValue={item?.project_id ?? ""} className="form-field"><option value="">No linked project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select><input name="position" type="number" defaultValue={item?.position ?? 0} className="form-field" /><ActionButton type="submit">{item ? "Save testimonial" : "Create testimonial"}</ActionButton></form>;
}

function PostForm({ item }: { item?: { id: string; slug: string; title: string; excerpt: string | null; cover_image: string | null; published: boolean } }) {
  return <form action={upsertBlogPostAction} className="grid gap-3 rounded-2xl border border-white/[.07] bg-black/10 p-4">{item ? <input type="hidden" name="id" value={item.id} /> : null}<div className="flex items-center justify-between gap-3">{item ? <StatusBadge value={item.published ? "published" : "draft"} /> : <span className="text-xs text-white/25">Draft</span>}<label className="flex items-center gap-2 text-xs text-white/45"><input name="published" type="checkbox" defaultChecked={item?.published} /> Published</label></div><input name="title" required defaultValue={item?.title ?? ""} placeholder="Article title" className="form-field" /><input name="slug" required defaultValue={item?.slug ?? ""} placeholder="article-slug" className="form-field" /><textarea name="excerpt" rows={4} defaultValue={item?.excerpt ?? ""} placeholder="Excerpt" className="form-field resize-y" /><input name="coverImage" defaultValue={item?.cover_image ?? ""} placeholder="Cover image URL" className="form-field" /><ActionButton type="submit">{item ? "Save article" : "Create article"}</ActionButton></form>;
}
